config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'
  get '/movies', to: 'movies#index'
  get '/lists', to: 'lists#index'
  get 'lists/new', to: 'lists#new', as: :list_add
  post 'lists', to: 'lists#create'
  get 'lists/:id', to: 'lists#show', as: :list
  get 'bookmark/:movie_id/:list_id', to: 'bookmarks#new', as: :bookmark_new
  post 'bookmarks', to: 'bookmarks#create'
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :bookmark_del
  delete 'lists/:id', to: 'lists#destroy', as: :delete_list
  post 'lists/:id', to: 'lists#create_comment', as: :list_comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :poster_img
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :comment, presence: true, length: { minimum: 10 }
  validates :poster_img, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :list_comments, dependent: :destroy
end

app/models/list_comment.rb
class ListComment < ApplicationRecord
  belongs_to :list
  validates :content, presence: true, length: { minimum: 15 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @movie = Movie.find(params[:movie_id])
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    list = bookmark.list
    bookmark.destroy!
    redirect_to list_path(list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
    @listcomment = ListComment.new
    @listcomments = ListComment.all
    @bookmarks = Bookmark.new
    @bookmarks = @list.bookmarks
  end

  def create_comment
    @listcomment = ListComment.new(listcomment_params)
    @listcomment.list = List.find(params[:id])
    if @listcomment.save
      redirect_to list_path(@listcomment.list)
    else
      @list = List.find(params[:id])
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :poster_img, :comment)
  end

  def listcomment_params
    params.require(:list_comment).permit(:content)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @lists = List.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1651204978999-00d7ce1b078a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1154&q=80);">
  <div class="container text-white">
    <h1>silly<strong>MovieDB</strong></h1>
    <p>Add movie to list</p>
  </div>
</div>
<div class="container my-5 bg-light py-5 shadow">
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <h3 class="text-muted">Add comment to the movie</h3>
    <hr class="text-secondary">
      <%= simple_form_for @bookmark do |f| %>
        <%= f.input :comment %>
        <%= f.input :movie_id, :as => :hidden, :input_html => { :value => params[:movie_id] } %>
        <%= f.input :list_id, :as => :hidden, :input_html => { :value => params[:list_id] } %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SillyMovieDB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1651204978999-00d7ce1b078a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1154&q=80);">
  <div class="container text-white">
    <h1>silly<strong>MovieDB</strong></h1>
    <p>Manage your lists</p>
  </div>
</div>
<% if @lists.count.zero? %>
  <div class="container text-center my-5 bg-light py-5 shadow">
    <h1 class="text-muted">Sorry, you have no list yet! </h1>
    <h2 class="text-secondary">Maybe create one <%= link_to "here", list_add_path %></h2>
  </div>
<% else %>
  <div class="container gap-3 d-flex flex-wrap  justify-content-center my-5 bg-light p-5 shadow">
    <% @lists.each do |list| %>
      <div class="card-product" style="width:30vw">
        <%= cl_image_tag list.poster_img.key %>
        <div class="card-product-infos">
          <h2><%= list.name %></h2>
          <p><%= list.comment %></p>
          <span>
          <%= link_to "Open List", list_path(list), class: "btn btn-dark my-2 btn-sm" %>
          <%= link_to "Delete",
            delete_list_path(list),
            class: "btn btn-danger text-white btn-sm",
            data: {turbo_method: :delete, turbo_confirm: "Do you want to delete this list?"}
          %>
        </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/lists/new.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1651204978999-00d7ce1b078a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1154&q=80);">
  <div class="container text-white">
    <h1>silly<strong>MovieDB</strong></h1>
    <p>Create a new list</p>
  </div>
</div>
<div class="container my-5 bg-light py-5 shadow">
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <h3 class="text-muted">Create a new list</h3>
    <hr class="text-secondary">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :poster_img, as: :file %>
        <%= f.input :comment %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.poster_img.key %>);">
  <div class="container text-white">
    <h1><%= @list.name %></h1>
    <p><%= @list.comment %></p>
  </div>
</div>
<% if @list.movies.count.zero? %>
  <div class="container text-center my-5 bg-light py-5 shadow">
    <h1 class="text-muted">This list has no movies </h1>
  </div>
<% else %>
  <h4 class="text-muted text-center mt-3"> You have bookmarked <%= pluralize(@list.movies.count, 'movie') %>! </h4>
  <div class="container gap-3 d-flex flex-wrap  justify-content-center my-3 bg-light p-5 shadow">
    <% @bookmarks.each do |bookmark| %>
      <div class="card-product movie" style="width:30vw">
        <%= image_tag(bookmark.movie.poster_url) %>
        <div class="card-product-infos">
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.movie.overview %></p>
          <%= link_to "Mark as watched",
            bookmark_del_path(bookmark),
            class: "btn btn-warning text-white mt-5 btn-sm",
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>
<div class="container my-3 bg-light p-5 shadow">
  <h2 class="text-muted text-center"> <%= pluralize(@listcomments.count, "other") %> commented...</h2>
  <hr>
  <% unless @listcomments.nil? %>
    <% @listcomments.each do |comment| %>
      <div class="card card-body py-2 text-muted my-2 shadow">
        <strong>Anonymous comment</strong>
        <hr>
        <%= comment.content %>
      </div>
    <% end %>
  <% end %>
  <div class="card card-body py-2 text-muted my-2 shadow">
    <%= simple_form_for @listcomment do |f| %>
      <%= f.input :content %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1651204978999-00d7ce1b078a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1154&q=80);">
  <div class="container text-white">
    <h1>silly<strong>MovieDB</strong></h1>
    <p>Welcome to the sillyMovieDB</p>
  </div>
</div>
<% if @movies.count.zero? %>
  <div class="container text-center my-5 bg-light py-5 shadow">
    <h1 class="text-muted">Sorry, no movies in the database </h1>
  </div>
<% else %>
  <h2 class="text-muted text-center flex-grow-1 mt-3" id="results_count"></h2>
  <div class="container gap-3 d-flex flex-wrap  justify-content-center my-5 bg-light p-5 shadow" data-controller="search">
    <input type="text" class="form-control m-4" placeholder="Type Something" id="search" name="searchbar" data-action="keyup->search#process">
    <% @movies.each do |movie| %>
      <div class="card-product movie" style="width:30vw">
        <%= image_tag(movie.poster_url) %>
        <div class="card-product-infos">
          <h2 class="name"><%= movie.title %></h2>
          <span data-controller="star-rating"></span>
          <p><%= movie.overview %></p>
          <div class="dropdown mt-3 float-end">
            <button class="btn dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid text-danger fa-bookmark"></i>
            </button>
            <ul class="dropdown-menu">
              <li><% @lists.each do |list| %>
                  <%= link_to list.name, bookmark_new_path(movie, list), class: "dropdown-item" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="banner py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1651204978999-00d7ce1b078a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1154&q=80);">
  <div class="container text-white">
    <h1>silly<strong>MovieDB</strong></h1>
    <p>Create, share and review your current movie and series watchlists!.</p>
  </div>
</div>

<div class="container d-flex flex-wrap gap-3 my-5 justify-content-center bg-light py-5 shadow">
  <div class="card-product">
  <img src="https://images.unsplash.com/photo-1512070679279-8988d32161be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=738&q=80" />
  <div class="card-product-infos">
    <h2>List All Movies</h2>
    <p>You can view a list of all current available movies.</p>
    <%= link_to "View Movies", movies_path, class: "btn btn-dark my-2 btn-sm" %>
  </div>
</div>

<div class="card-product">
  <img src="https://plus.unsplash.com/premium_photo-1682125742711-7fa55b842942?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1123&q=80" />
  <div class="card-product-infos">
    <h2>View My Lists</h2>
    <p>You can view& manage your current watchlists</p>
    <%= link_to "View Lists", lists_path, class: "btn btn-dark my-2 btn-sm" %>
  </div>
</div>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://www.pngitem.com/pimgs/m/466-4663233_cinema-icon-cinema-logo-png-transparent-png.png" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Movies DB", movies_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add List", list_add_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>